import numpy as np
import matplotlib.pyplot as plt

data = eval("""[['technician', 'administrator', 'administrator', 'student',
'lawyer', 'other', 'scientist', 'entertainment', 'librarian', 'artist',
'engineer', 'writer', 'student', 'artist', 'student', 'administrator',
'student', 'student', 'other', 'entertainment', 'administrator', 'librarian',
'programmer', 'marketing', 'student', 'executive', 'librarian', 'none',
'educator', 'healthcare', 'educator', 'student', 'administrator', 'scientist',
'other', 'executive', 'administrator', 'librarian', 'administrator',
'educator', 'marketing', 'artist', 'artist', 'student', 'other', 'salesman',
'executive', 'student', 'administrator', 'programmer', 'writer', 'lawyer',
'lawyer', 'none', 'none', 'programmer', 'other', 'educator', 'doctor',
'student', 'student', 'programmer', 'technician', 'entertainment', 'artist',
'librarian', 'artist', 'administrator', 'educator', 'engineer', 'educator',
'student', 'healthcare', 'educator', 'other', 'other', 'other', 'healthcare',
'educator', 'other', 'administrator', 'scientist', 'other', 'librarian',
'executive', 'student', 'artist', 'writer', 'technician', 'programmer',
'engineer', 'engineer', 'executive', 'administrator', 'student', 'librarian',
'engineer', 'administrator', 'educator', 'student', 'executive', 'doctor',
'engineer', 'librarian', 'none', 'student', 'student', 'student', 'artist',
'administrator', 'programmer', 'writer', 'executive', 'engineer', 'student',
'scientist', 'student', 'librarian', 'programmer', 'librarian', 'programmer',
'programmer', 'student', 'salesman', 'student', 'programmer', 'technician',
'educator', 'administrator', 'executive', 'programmer', 'student', 'scientist',
'technician', 'other', 'student', 'administrator', 'retired', 'programmer',
'student', 'student', 'student', 'educator', 'student', 'other', 'executive',
'scientist', 'lawyer', 'engineer', 'student', 'engineer', 'student', 'student',
'student', 'educator', 'student', 'executive', 'student', 'homemaker',
'engineer', 'student', 'student', 'student', 'engineer', 'student', 'other',
'executive', 'entertainment', 'student', 'programmer', 'artist',
'administrator', 'programmer', 'salesman', 'other', 'writer', 'student',
'administrator', 'other', 'engineer', 'engineer', 'other', 'educator',
'programmer', 'educator', 'student', 'lawyer', 'marketing', 'doctor',
'student', 'marketing', 'entertainment', 'student', 'administrator',
'administrator', 'administrator', 'other', 'technician', 'lawyer', 'educator',
'salesman', 'student', 'student', 'writer', 'engineer', 'educator', 'student',
'student', 'executive', 'student', 'retired', 'student', 'student', 'engineer',
'other', 'engineer', 'engineer', 'student', 'student', 'writer', 'programmer',
'writer', 'student', 'other', 'administrator', 'writer', 'other', 'healthcare',
'engineer', 'administrator', 'student', 'administrator', 'engineer', 'student',
'student', 'educator', 'engineer', 'administrator', 'engineer', 'student',
'technician', 'executive', 'writer', 'scientist', 'student', 'programmer',
'educator', 'scientist', 'educator', 'educator', 'writer', 'writer',
'librarian', 'student', 'educator', 'executive', 'student', 'student',
'engineer', 'librarian', 'student', 'lawyer', 'educator', 'artist', 'other',
'marketing', 'student', 'programmer', 'other', 'programmer', 'educator',
'programmer', 'librarian', 'educator', 'scientist', 'writer', 'student',
'student', 'none', 'other', 'engineer', 'educator', 'student', 'student',
'retired', 'educator', 'student', 'student', 'programmer', 'writer',
'technician', 'programmer', 'educator', 'student', 'programmer', 'other',
'lawyer', 'marketing', 'educator', 'administrator', 'other', 'educator',
'programmer', 'other', 'librarian', 'educator', 'student', 'student', 'other',
'student', 'engineer', 'administrator', 'technician', 'technician',
'administrator', 'entertainment', 'homemaker', 'student', 'executive', 'other',
'technician', 'other', 'other', 'other', 'student', 'student', 'other',
'educator', 'engineer', 'student', 'student', 'writer', 'programmer',
'student', 'programmer', 'marketing', 'administrator', 'engineer', 'educator',
'student', 'educator', 'writer', 'writer', 'programmer', 'writer',
'administrator', 'educator', 'healthcare', 'salesman', 'other', 'educator',
'other', 'other', 'student', 'administrator', 'engineer', 'artist', 'engineer',
'artist', 'other', 'executive', 'student', 'artist', 'doctor', 'writer',
'lawyer', 'engineer', 'student', 'technician', 'other', 'administrator',
'other', 'student', 'executive', 'programmer', 'scientist', 'student',
'student', 'other', 'administrator', 'engineer', 'student', 'scientist',
'administrator', 'other', 'student', 'other', 'executive', 'educator',
'student', 'other', 'educator', 'student', 'programmer', 'student', 'educator',
'educator', 'engineer', 'doctor', 'other', 'student', 'student', 'librarian'],
['technician', 'other', 'other', 'other', 'educator', 'other', 'writer',
'writer', 'artist', 'librarian', 'programmer', 'student', 'homemaker',
'engineer', 'technician', 'marketing', 'administrator', 'writer', 'educator',
'programmer', 'programmer', 'programmer', 'administrator', 'educator',
'student', 'engineer', 'engineer', 'student', 'entertainment', 'technician',
'administrator', 'administrator', 'administrator', 'student', 'programmer',
'educator', 'administrator', 'entertainment', 'executive', 'student',
'administrator', 'executive', 'student', 'student', 'engineer', 'retired',
'scientist', 'educator', 'student', 'programmer', 'engineer', 'student',
'marketing', 'administrator', 'student', 'other', 'programmer', 'engineer',
'student', 'programmer', 'artist', 'other', 'scientist', 'programmer',
'entertainment', 'administrator', 'executive', 'programmer', 'librarian',
'educator', 'administrator', 'administrator', 'educator', 'scientist',
'student', 'lawyer', 'educator', 'librarian', 'programmer', 'engineer',
'administrator', 'programmer', 'librarian', 'student', 'programmer', 'student',
'student', 'scientist', 'educator', 'administrator', 'artist', 'educator',
'educator', 'technician', 'student', 'student', 'engineer', 'student',
'educator', 'entertainment', 'administrator', 'engineer', 'student',
'administrator', 'student', 'administrator', 'executive', 'marketing', 'none',
'engineer', 'educator', 'doctor', 'educator', 'student', 'student', 'student',
'retired', 'educator', 'marketing', 'educator', 'student', 'administrator',
'entertainment', 'librarian', 'librarian', 'other', 'librarian', 'librarian',
'other', 'retired', 'programmer', 'librarian', 'homemaker', 'educator',
'other', 'student', 'student', 'lawyer', 'student', 'other', 'student',
'entertainment', 'writer', 'writer', 'student', 'student', 'other', 'other',
'administrator', 'programmer', 'educator', 'engineer', 'student',
'administrator', 'educator', 'educator', 'other', 'educator', 'programmer',
'entertainment', 'other', 'student', 'educator', 'student', 'artist',
'engineer', 'student', 'salesman', 'administrator', 'librarian', 'student',
'administrator', 'student', 'administrator', 'technician', 'technician',
'student', 'engineer', 'programmer', 'student', 'programmer', 'student',
'other', 'educator', 'educator', 'writer', 'administrator', 'student',
'student', 'programmer', 'administrator', 'writer', 'other', 'marketing',
'other', 'programmer', 'marketing', 'librarian', 'student', 'student',
'educator', 'administrator', 'librarian', 'salesman', 'librarian', 'scientist',
'student', 'scientist', 'educator', 'other', 'executive', 'student',
'administrator', 'retired', 'student', 'entertainment', 'educator', 'educator',
'student', 'student', 'student', 'other', 'librarian', 'student', 'programmer',
'engineer', 'healthcare', 'marketing', 'educator', 'educator', 'student',
'programmer', 'educator', 'programmer', 'engineer', 'healthcare', 'student',
'student', 'other', 'engineer', 'student', 'scientist', 'programmer',
'engineer', 'other', 'programmer', 'educator', 'librarian', 'other',
'engineer', 'administrator', 'administrator', 'librarian', 'administrator',
'educator', 'student', 'programmer', 'student', 'salesman', 'writer', 'other',
'other', 'librarian', 'homemaker', 'student', 'student', 'technician',
'student', 'student', 'scientist', 'programmer', 'technician', 'educator',
'writer', 'programmer', 'marketing', 'engineer', 'administrator',
'administrator', 'retired', 'librarian', 'educator', 'student', 'student',
'scientist', 'other', 'executive', 'executive', 'librarian', 'student',
'engineer', 'administrator', 'other', 'technician', 'programmer',
'administrator', 'other', 'marketing', 'marketing', 'technician', 'student',
'librarian', 'student', 'engineer', 'writer', 'programmer', 'technician',
'artist', 'entertainment', 'engineer', 'marketing', 'administrator', 'retired',
'student', 'executive', 'scientist', 'other', 'student', 'marketing',
'librarian', 'engineer', 'other', 'student', 'technician', 'student',
'educator', 'librarian', 'homemaker', 'other', 'other', 'librarian', 'writer',
'engineer', 'student', 'other', 'student', 'administrator', 'other',
'entertainment', 'technician', 'student'], ['writer', 'executive', 'educator',
'programmer', 'homemaker', 'engineer', 'scientist', 'student', 'engineer',
'marketing', 'student', 'scientist', 'student', 'executive', 'programmer',
'student', 'engineer', 'healthcare', 'other', 'librarian', 'artist',
'marketing', 'other', 'engineer', 'marketing', 'student', 'other', 'educator',
'lawyer', 'administrator', 'marketing', 'scientist', 'student',
'administrator', 'student', 'writer', 'writer', 'educator', 'librarian',
'student', 'marketing', 'educator', 'salesman', 'other', 'educator',
'executive', 'student', 'librarian', 'retired', 'writer', 'student', 'student',
'engineer', 'librarian', 'other', 'engineer', 'writer', 'programmer', 'other',
'other', 'educator', 'technician', 'administrator', 'student', 'educator',
'salesman', 'scientist', 'writer', 'engineer', 'engineer', 'writer',
'healthcare', 'healthcare', 'artist', 'none', 'scientist', 'other', 'writer',
'educator', 'entertainment', 'other', 'other', 'student', 'healthcare',
'other', 'retired', 'scientist', 'educator', 'technician', 'artist',
'educator', 'writer', 'administrator', 'marketing', 'engineer', 'other',
'engineer', 'educator', 'educator', 'artist', 'educator', 'retired',
'marketing', 'administrator', 'other', 'educator', 'educator', 'artist',
'other', 'student', 'student', 'writer', 'student', 'scientist', 'programmer',
'other', 'librarian', 'student', 'engineer', 'retired', 'executive',
'healthcare', 'educator', 'none', 'student', 'other', 'other', 'librarian',
'librarian', 'healthcare', 'engineer', 'healthcare', 'programmer', 'student',
'other', 'librarian', 'other', 'other', 'executive', 'executive',
'administrator', 'educator', 'other', 'other', 'healthcare', 'writer',
'student', 'writer', 'salesman', 'none', 'administrator', 'student',
'administrator', 'student', 'student', 'student', 'artist', 'student',
'programmer', 'other', 'administrator', 'other', 'librarian', 'other',
'librarian', 'other', 'writer', 'artist', 'librarian', 'doctor', 'student',
'writer', 'student', 'librarian', 'educator', 'artist', 'other', 'programmer',
'student', 'student', 'administrator', 'educator', 'writer', 'retired',
'artist', 'librarian', 'healthcare', 'other', 'student', 'other',
'entertainment', 'scientist', 'artist', 'salesman', 'scientist', 'scientist',
'student', 'educator', 'administrator']]""")


for x in range(3):
    d = {}
    for o in data[x]:
        if o in d:
            d[o] += 1
        else:
            d[o] = 1
        plt.figure(x+1)
    plt.title("Occupation Distribution for Cluster " + str(x))
    plt.pie(d.values(), labels=d.keys())

plt.show()
